services:
  db:
    image: mysql:8.0
    container_name: estoquedb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: estoque
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  app:
    build: .
    container_name: estoquespring
    ports: 
      - "8080:8080"
    depends_on: 
      - db